import QtQuick
import QtQuick.Layouts
import QtQuick.Controls
import Quickshell
import Quickshell.Io

/*
 * AnimationsPage v6.16.3.4.3
 *
 * Changes vs v6.16.3.4.2:
 *   (1) Current-preset DETECTION — previously the page only read its own
 *       state JSON (animation-state.json), so on fresh installs or after
 *       manual edits the dropdown always showed "Default (Current)" even
 *       when Hyprland was running a different animation config.
 *
 *       Fix: also read ~/.config/hypr/modules/animations.conf and match
 *       its content against the known preset dictionary. Priority order:
 *         1. Parse "# Generated by Zen Settings — preset: <n>" header
 *            (fastest, set by our own writer)
 *         2. Normalized content match against preset dict
 *         3. If neither matches → synthesize "Custom (External Edit)"
 *            pseudo-preset showing current live config read-only.
 *       Additionally FileView watchChanges so external edits (or other
 *       tools that touch animations.conf) update the page in real time.
 *
 *   (2) Scroll-cutoff FIX — the ColumnLayout was positioned with
 *       `x: 24; y: 24` inside the ScrollView. ScrollView's auto-
 *       contentHeight didn't properly account for the 24px y-offset,
 *       and the trailing spacer was only 24px — so the last widget
 *       (PageFooter / Reset) was clipped at the bottom.
 *
 *       Fix: wrap the ColumnLayout in an Item that explicitly reports
 *       implicitHeight = contentCol.y + contentCol.implicitHeight + 48.
 *       Bottom spacer bumped to 48px for visual breathing room.
 *
 * Wala tayong babawasan — all 21 preset strings carried byte-identical
 * from v6.16.3.4.2. No preset removed, no feature dropped.
 */
ScrollView {
    id: root
    clip: true
    // v6.16.3.4.3: explicit contentWidth so the ScrollView sizes its
    // viewport correctly. Matches the BatterySettingsPage pattern.
    contentWidth: availableWidth

    // ── Current preset state ──
    property string currentPreset: "Default (Current)"

    // v6.16.3.4.3: tracks whether the user has an external/manual edit
    // that doesn't match any known preset. When true, the ComboBox
    // includes a "Custom (External Edit)" entry at the top.
    property bool externalEdit: false
    property string externalEditContent: ""

    readonly property string animStatePath: Quickshell.env("HOME") + "/.config/quickshell/zen-shell/animation-state.json"
    readonly property string liveConfPath:  Quickshell.env("HOME") + "/.config/hypr/modules/animations.conf"

    function saveAnimState() {
        animStateSaver.command = ["bash", "-c",
            "mkdir -p $(dirname '" + animStatePath + "') && " +
            "echo '{\"preset\":\"" + currentPreset.replace(/"/g, '\\"') + "\"}' > '" + animStatePath + "'"]
        animStateSaver.running = true
    }
    Process { id: animStateSaver; running: false }

    FileView {
        id: animStateLoader
        path: root.animStatePath
        blockLoading: false
        onLoaded: {
            try {
                const s = JSON.parse(this.text())
                if (s.preset && root.presetNames.indexOf(s.preset) >= 0) {
                    // Seed with saved choice, but live-conf read below may override.
                    root.currentPreset = s.preset
                }
            } catch (e) {}
        }
    }

    // v6.16.3.4.3: Read the ACTUAL animations.conf Hyprland is using and
    // reconcile it against the known presets. This is the source of truth.
    FileView {
        id: liveConfLoader
        path: root.liveConfPath
        blockLoading: false
        watchChanges: true
        onLoaded:       root._reconcileLiveConf(this.text())
        onFileChanged:  this.reload()
    }

    Component.onCompleted: {
        animStateLoader.reload()
        liveConfLoader.reload()
    }

    // ── Preset list ──
    // v6.16.3.4.3: when externalEdit is true, we prepend a synthesized
    // "Custom (External Edit)" entry so the dropdown accurately reflects
    // that the live config doesn't match any bundled preset. The base
    // presetNames list stays untouched for applyPreset() lookups.
    readonly property var presetNames: [
        "Default (Current)", "Classic", "HyDe Diablo-1", "HyDe Diablo-2",
        "Disabled", "HyDe Dynamic", "End4 Animation", "Fast", "High",
        "Ja (JaKooLit)", "LimeFrenzy", "Me-1", "Me-2", "Minimal-1",
        "Minimal-2", "Moving", "Optimized", "Standard", "Vertical",
        "Elifouts", "Linuxfam"
    ]

    readonly property var displayPresetNames: {
        if (externalEdit) return ["Custom (External Edit)"].concat(presetNames)
        return presetNames
    }

    readonly property var presets: ({
"Default (Current)": "animations {\n    enabled = yes, please :)\n    bezier = easeOutQuint, 0.23, 1, 0.32, 1\n    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1\n    bezier = linear, 0, 0, 1, 1\n    bezier = almostLinear, 0.5, 0.5, 0.75, 1\n    bezier = quick, 0.15, 0, 0.1, 1\n    animation = global, 1, 10, default\n    animation = border, 1, 5.39, easeOutQuint\n    animation = windows, 1, 4.79, easeOutQuint\n    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%\n    animation = windowsOut, 1, 1.49, linear, popin 87%\n    animation = fadeIn, 1, 1.73, almostLinear\n    animation = fadeOut, 1, 1.46, almostLinear\n    animation = fade, 1, 3.03, quick\n    animation = layers, 1, 3.81, easeOutQuint\n    animation = layersIn, 1, 4, easeOutQuint, fade\n    animation = layersOut, 1, 1.5, linear, fade\n    animation = fadeLayersIn, 1, 1.79, almostLinear\n    animation = fadeLayersOut, 1, 1.39, almostLinear\n    animation = workspaces, 1, 1.94, almostLinear, fade\n    animation = workspacesIn, 1, 1.21, almostLinear, fade\n    animation = workspacesOut, 1, 1.94, almostLinear, fade\n    animation = zoomFactor, 1, 7, quick\n}",
"Classic": "animations {\n    enabled = true\n    bezier = myBezier, 0.05, 0.9, 0.1, 1.05\n    animation = windows, 1, 7, myBezier\n    animation = windowsOut, 1, 7, default, popin 80%\n    animation = border, 1, 10, default\n    animation = borderangle, 1, 8, default\n    animation = fade, 1, 7, default\n    animation = workspaces, 1, 6, default\n}",
"HyDe Diablo-1": "animations {\n    enabled = 1\n    bezier = default, 0.05, 0.9, 0.1, 1.05\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = overshot, 0.13, 0.99, 0.29, 1.08\n    bezier = liner, 1, 1, 1, 1\n    bezier = bounce, 0.4, 0.9, 0.6, 1.0\n    bezier = snappyReturn, 0.4, 0.9, 0.6, 1.0\n    animation = windows, 1, 5, snappyReturn, slidevert\n    animation = windowsIn, 1, 5, snappyReturn, slidevert right\n    animation = windowsOut, 1, 5, snappyReturn, slide\n    animation = windowsMove, 1, 6, bounce, slide\n    animation = layersOut, 1, 5, bounce, slidevert right\n    animation = fadeIn, 1, 10, default\n    animation = fadeOut, 1, 10, default\n    animation = workspaces, 1, 7, overshot, slidevert\n    animation = border, 1, 1, liner\n    animation = layers, 1, 4, bounce, slidevert right\n    animation = borderangle, 1, 30, liner, loop\n}",
"HyDe Diablo-2": "animations {\n    enabled = 1\n    bezier = default, 0.05, 0.9, 0.1, 1.05\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = overshot, 0.13, 0.99, 0.29, 1.08\n    bezier = liner, 1, 1, 1, 1\n    animation = windows, 1, 7, wind, popin\n    animation = windowsIn, 1, 7, overshot, popin\n    animation = windowsOut, 1, 5, overshot, popin\n    animation = windowsMove, 1, 6, overshot, slide\n    animation = layers, 1, 5, default, popin\n    animation = fadeIn, 1, 10, default\n    animation = fadeOut, 1, 10, default\n    animation = workspaces, 1, 7, overshot, slidevert\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 30, liner, loop\n}",
"Disabled": "animations {\n    enabled = false\n}",
"HyDe Dynamic": "animations {\n    enabled = true\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = winIn, 0.1, 1.1, 0.1, 1.1\n    bezier = winOut, 0.3, -0.3, 0, 1\n    bezier = liner, 1, 1, 1, 1\n    animation = windows, 1, 6, wind, slide\n    animation = windowsIn, 1, 6, winIn, slide\n    animation = windowsOut, 1, 5, winOut, slide\n    animation = windowsMove, 1, 5, wind, slide\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 30, liner, loop\n    animation = fade, 1, 10, default\n    animation = workspaces, 1, 5, wind\n}",
"End4 Animation": "animations {\n    enabled = true\n    bezier = md3_decel, 0.05, 0.7, 0.1, 1\n    bezier = md3_accel, 0.3, 0, 0.8, 0.15\n    bezier = overshot, 0.05, 0.9, 0.1, 1.1\n    bezier = menu_decel, 0.1, 1, 0, 1\n    bezier = menu_accel, 0.38, 0.04, 1, 0.07\n    animation = windows, 1, 3, md3_decel, popin 60%\n    animation = windowsIn, 1, 3, md3_decel, popin 60%\n    animation = windowsOut, 1, 3, md3_accel, popin 60%\n    animation = border, 1, 10, default\n    animation = fade, 1, 3, md3_decel\n    animation = layersIn, 1, 3, menu_decel, slide\n    animation = layersOut, 1, 1.6, menu_accel\n    animation = fadeLayersIn, 1, 2, menu_decel\n    animation = fadeLayersOut, 1, 4.5, menu_accel\n    animation = workspaces, 1, 7, menu_decel, slide\n    animation = specialWorkspace, 1, 3, md3_decel, slidevert\n}",
"Fast": "animations {\n    enabled = true\n    bezier = md3_decel, 0.05, 0.7, 0.1, 1\n    animation = windows, 1, 3, md3_decel, popin 60%\n    animation = border, 1, 10, default\n    animation = fade, 1, 2.5, md3_decel\n    animation = workspaces, 1, 3.5, md3_decel, slide\n}",
"High": "animations {\n    enabled = true\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = winIn, 0.1, 1.1, 0.1, 1.1\n    bezier = winOut, 0.3, -0.3, 0, 1\n    bezier = liner, 1, 1, 1, 1\n    animation = windows, 1, 6, wind, slide\n    animation = windowsIn, 1, 6, winIn, slide\n    animation = windowsOut, 1, 5, winOut, slide\n    animation = windowsMove, 1, 5, wind, slide\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 30, liner, loop\n    animation = fade, 1, 10, default\n    animation = workspaces, 1, 5, wind\n}",
"Ja (JaKooLit)": "animations {\n    enabled = yes\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = winIn, 0.1, 1.1, 0.1, 1.1\n    bezier = winOut, 0.3, -0.3, 0, 1\n    bezier = liner, 1, 1, 1, 1\n    bezier = overshot, 0.05, 0.9, 0.1, 1.05\n    bezier = smoothOut, 0.5, 0, 0.99, 0.99\n    bezier = smoothIn, 0.5, -0.5, 0.68, 1.5\n    animation = windows, 1, 6, wind, slide\n    animation = windowsIn, 1, 5, winIn, slide\n    animation = windowsOut, 1, 3, smoothOut, slide\n    animation = windowsMove, 1, 5, wind, slide\n    animation = border, 1, 1, liner\n    animation = fade, 1, 3, smoothOut\n    animation = workspaces, 1, 5, overshot\n}",
"LimeFrenzy": "animations {\n    enabled = 1\n    bezier = overshot, 0.18, 0.95, 0.22, 1.03\n    bezier = liner, 1, 1, 1, 1\n    animation = windows, 1, 5, overshot, popin 60%\n    animation = windowsIn, 1, 6, overshot, popin 60%\n    animation = windowsOut, 1, 4, overshot, popin 60%\n    animation = layers, 1, 4, default, popin\n    animation = fadeIn, 1, 7, default\n    animation = fadeOut, 1, 7, default\n    animation = workspaces, 1, 5, overshot, slidevert\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 24, liner, loop\n}",
"Me-1": "animations {\n    enabled = true\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = winIn, 0.1, 1.1, 0.1, 1.1\n    bezier = liner, 1, 1, 1, 1\n    bezier = md3_decel, 0.05, 0.7, 0.1, 1\n    bezier = menu_decel, 0.1, 1, 0, 1\n    bezier = menu_accel, 0.38, 0.04, 1, 0.07\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 30, liner, loop\n    animation = windows, 1, 6, wind, slide\n    animation = windowsIn, 1, 6, winIn, slide\n    animation = windowsOut, 1, 5, wind, slide\n    animation = windowsMove, 1, 5, wind, slide\n    animation = fade, 1, 3, md3_decel\n    animation = layersIn, 1, 3, menu_decel, slide\n    animation = layersOut, 1, 1.6, menu_accel\n    animation = fadeLayersIn, 1, 2, menu_decel\n    animation = fadeLayersOut, 1, 4.5, menu_accel\n    animation = workspaces, 1, 7, menu_decel, slide\n    animation = specialWorkspace, 1, 3, md3_decel, slidevert\n}",
"Me-2": "animations {\n    enabled = true\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = winIn, 0.1, 1.1, 0.1, 1.1\n    bezier = liner, 1, 1, 1, 1\n    bezier = md3_decel, 0.05, 0.7, 0.1, 1\n    bezier = menu_decel, 0.1, 1, 0, 1\n    bezier = menu_accel, 0.38, 0.04, 1, 0.07\n    bezier = OutBack, 0.34, 1.56, 0.64, 1\n    bezier = easeInOutCirc, 0.85, 0, 0.15, 1\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 30, liner, loop\n    animation = windowsIn, 1, 6, winIn, slide\n    animation = windows, 1, 5, easeInOutCirc\n    animation = windowsOut, 1, 5, OutBack\n    animation = windowsMove, 1, 5, wind, slide\n    animation = fade, 1, 3, md3_decel\n    animation = layersIn, 1, 3, menu_decel, slide\n    animation = layersOut, 1, 1.6, menu_accel\n    animation = fadeLayersIn, 1, 2, menu_decel\n    animation = fadeLayersOut, 1, 4.5, menu_accel\n    animation = workspaces, 1, 7, menu_decel, slide\n    animation = specialWorkspace, 1, 3, md3_decel, slidevert\n}",
"Minimal-1": "animations {\n    enabled = true\n    bezier = wind, 0.05, 0.9, 0.1, 1.05\n    bezier = liner, 1, 1, 1, 1\n    animation = windows, 1, 6, wind, slide\n    animation = windowsIn, 1, 6, wind, slide\n    animation = windowsOut, 1, 5, wind, slide\n    animation = windowsMove, 1, 5, wind, slide\n    animation = border, 1, 1, liner\n    animation = borderangle, 1, 30, liner, loop\n    animation = fade, 1, 10, default\n    animation = workspaces, 1, 5, wind\n}",
"Minimal-2": "animations {\n    enabled = yes\n    bezier = quart, 0.25, 1, 0.5, 1\n    animation = windows, 1, 6, quart, slide\n    animation = border, 1, 6, quart\n    animation = borderangle, 1, 6, quart\n    animation = fade, 1, 6, quart\n    animation = workspaces, 1, 6, quart\n}",
"Moving": "animations {\n    enabled = true\n    bezier = overshot, 0.05, 0.9, 0.1, 1.05\n    bezier = smoothOut, 0.5, 0, 0.99, 0.99\n    bezier = smoothIn, 0.5, -0.5, 0.68, 1.5\n    animation = windows, 1, 5, overshot, slide\n    animation = windowsOut, 1, 3, smoothOut\n    animation = windowsIn, 1, 3, smoothOut\n    animation = windowsMove, 1, 4, smoothIn, slide\n    animation = border, 1, 5, default\n    animation = fade, 1, 5, smoothIn\n    animation = fadeDim, 1, 5, smoothIn\n    animation = workspaces, 1, 6, default\n}",
"Optimized": "animations {\n    enabled = true\n    bezier = wind, 0.05, 0.85, 0.03, 0.97\n    bezier = winIn, 0.07, 0.88, 0.04, 0.99\n    bezier = liner, 1, 1, 1, 1\n    bezier = md3_decel, 0.05, 0.80, 0.10, 0.97\n    bezier = menu_decel, 0.05, 0.82, 0, 1\n    bezier = menu_accel, 0.20, 0, 0.82, 0.10\n    bezier = easeOutCirc, 0, 0.48, 0.38, 1\n    animation = border, 1, 1.6, liner\n    animation = borderangle, 1, 82, liner, loop\n    animation = windowsIn, 1, 3.2, winIn, slide\n    animation = windowsOut, 1, 2.8, easeOutCirc\n    animation = windowsMove, 1, 3.0, wind, slide\n    animation = fade, 1, 1.8, md3_decel\n    animation = layersIn, 1, 1.8, menu_decel, slide\n    animation = layersOut, 1, 1.5, menu_accel\n    animation = fadeLayersIn, 1, 1.6, menu_decel\n    animation = fadeLayersOut, 1, 1.8, menu_accel\n    animation = workspaces, 1, 4.0, menu_decel, slide\n    animation = specialWorkspace, 1, 2.3, md3_decel, slidefadevert 15%\n}",
"Standard": "animations {\n    enabled = true\n    bezier = myBezier, 0.05, 0.9, 0.1, 1.05\n    animation = windows, 1, 7, myBezier\n    animation = windowsOut, 1, 7, default, popin 80%\n    animation = border, 1, 10, default\n    animation = borderangle, 1, 8, default\n    animation = fade, 1, 7, default\n    animation = workspaces, 1, 6, default\n}",
"Vertical": "animations {\n    bezier = fluent_decel, 0, 0.2, 0.4, 1\n    bezier = easeOutCirc, 0, 0.55, 0.45, 1\n    bezier = easeOutCubic, 0.33, 1, 0.68, 1\n    bezier = easeinoutsine, 0.37, 0, 0.63, 1\n    animation = windowsIn, 1, 1.5, easeinoutsine, popin 60%\n    animation = windowsOut, 1, 1.5, easeOutCubic, popin 60%\n    animation = windowsMove, 1, 1.5, easeinoutsine, slide\n    animation = fade, 1, 2.5, fluent_decel\n    animation = fadeLayersIn, 0\n    animation = border, 0\n    animation = layers, 1, 1.5, easeinoutsine, popin\n    animation = workspaces, 1, 3, fluent_decel, slidefadevert 30%\n    animation = specialWorkspace, 1, 2, fluent_decel, slidefade 10%\n}",
"Elifouts": "animations {\n    enabled = true\n    bezier = fluid, 0.15, 0.85, 0.25, 1\n    bezier = snappy, 0.3, 1, 0.4, 1\n    animation = windows, 1, 3, fluid, popin 5%\n    animation = windowsOut, 1, 2.5, snappy\n    animation = fade, 1, 4, snappy\n    animation = workspaces, 1, 1.7, snappy, slide\n    animation = specialWorkspace, 1, 4, fluid, slidefadevert -35%\n    animation = layers, 1, 2, snappy, popin 70%\n}",
"Linuxfam": "animations {\n    enabled = true\n    bezier = myBezier, 0.05, 0.9, 0.1, 1.05\n    animation = windows, 1, 7, myBezier\n    animation = windowsIn, 1, 8, default, slide bottom\n    animation = windowsOut, 1, 7, default, slide right\n    animation = border, 1, 10, default\n    animation = borderangle, 1, 8, default\n    animation = fade, 1, 7, default\n    animation = workspaces, 1, 6, default\n}"
    })

    function applyPreset(name) {
        if (!presets[name]) return
        currentPreset = name
        externalEdit = false              // applying a known preset clears custom flag
        externalEditContent = ""
        saveAnimState()
        const path = Quickshell.env("HOME") + "/.config/hypr/modules/animations.conf"
        const content = "# Generated by Zen Settings — preset: " + name + "\n" + presets[name] + "\n"
        writeProc.command = ["bash", "-c",
            "mkdir -p $(dirname '" + path + "') && cat > '" + path + "' << 'ZENEOF'\n" + content + "\nZENEOF\n" +
            "hyprctl reload && echo OK"]
        writeProc.running = true
    }

    // v6.16.1.6: After `hyprctl reload`, Hyprland re-parses ~/.config/hypr/hyprland.conf
    // from scratch, which WIPES all runtime-applied keyword values from SettingsStateV2
    // (gaps, borders, rounding, blur, etc. reset to hyprland.conf defaults). Settings
    // appeared to "come back" only when the user opened Themes page because that re-
    // triggers applyToHyprland(). Fix: after reload completes, immediately re-push
    // SettingsStateV2's saved values so the user sees their configured state preserved.
    Process { id: writeProc; running: false
        onExited: (exitCode) => {
            if (typeof SettingsStateV2 !== "undefined" && exitCode === 0) {
                Qt.callLater(SettingsStateV2.applyToHyprland)
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // v6.16.3.4.3 — Reconcile live animations.conf with preset dict
    // ═══════════════════════════════════════════════════════════════
    //
    // Strategy:
    //   1. If the first line is "# Generated by Zen Settings — preset: X",
    //      trust it (fast path — our own writer produced this file).
    //   2. Strip the header and normalize whitespace. Compare normalized
    //      content against each preset. Use normalized equality.
    //   3. No match → mark externalEdit = true so UI shows
    //      "Custom (External Edit)".
    //
    // Normalization rules:
    //   - Collapse runs of whitespace → single space
    //   - Drop empty lines and comment lines
    //   - Trim both ends
    //
    // This tolerates formatting drift (user edits indentation, inserts
    // blank lines) without misreporting unchanged configs as custom.
    function _normalize(text) {
        if (!text) return ""
        const lines = text.split("\n")
        const out = []
        for (let i = 0; i < lines.length; i++) {
            let l = lines[i].replace(/\s+/g, " ").trim()
            if (l === "") continue
            if (l.charAt(0) === "#") continue
            out.push(l)
        }
        return out.join(" ")
    }

    function _reconcileLiveConf(text) {
        if (!text) {
            // File doesn't exist yet — keep whatever state JSON seeded us with
            return
        }

        // (1) Fast path: header comment declares the preset
        const headerMatch = text.match(/#\s*Generated by Zen Settings\s*[—-]\s*preset:\s*(.+)/)
        if (headerMatch) {
            const headerName = headerMatch[1].trim()
            if (root.presetNames.indexOf(headerName) >= 0) {
                root.currentPreset = headerName
                root.externalEdit = false
                root.externalEditContent = ""
                return
            }
        }

        // (2) Content match against preset dict
        const normLive = _normalize(text)
        const names = root.presetNames
        for (let i = 0; i < names.length; i++) {
            const name = names[i]
            const normPreset = _normalize(root.presets[name])
            if (normLive === normPreset) {
                root.currentPreset = name
                root.externalEdit = false
                root.externalEditContent = ""
                return
            }
        }

        // (3) No match — external edit
        root.externalEdit = true
        root.externalEditContent = text
        root.currentPreset = "Custom (External Edit)"
        console.log("[AnimationsPage] live animations.conf doesn't match any known preset — marked as Custom (External Edit)")
    }

    // ═══════════════════════════════════════════════════════════════
    // v6.16.3.4.3 — Content wrapper for proper ScrollView height
    // ═══════════════════════════════════════════════════════════════
    //
    // Wrapping the ColumnLayout in an Item whose implicitHeight explicitly
    // accounts for the y-offset + bottom padding ensures ScrollView can
    // scroll all the way to the last widget. Without this wrapper, the
    // PageFooter was clipped because ScrollView auto-height calculation
    // didn't include the 24px top offset.
    Item {
        implicitWidth: root.availableWidth
        implicitHeight: contentCol.y + contentCol.implicitHeight + 48

        ColumnLayout {
            id: contentCol
            width: root.availableWidth - 48
            x: 24; y: 24
            spacing: 16

            ColumnLayout {
                Layout.fillWidth: true
                spacing: 4
                Text {
                    text: "Animations"
                    font.family: Theme.fontFamily
                    font.pixelSize: 22
                    font.weight: Font.Bold
                    color: ThemeService.fg
                }
                Text {
                    text: "21 community presets — auto-applies to Hyprland"
                    font.family: Theme.fontFamily
                    font.pixelSize: 12
                    color: ThemeService.grey1
                }
            }

            ControlCenterBanner {
                feature: "Animation Bezier Editor"
                description: "Custom curves, per-animation tuning"
            }

            // v6.16.3.4.3: External-edit diagnostic banner — only visible when
            // the live animations.conf doesn't match any known preset. Gives
            // the user a clear "this is custom" indicator plus a one-click
            // revert to Default.
            Rectangle {
                visible: root.externalEdit
                Layout.fillWidth: true
                Layout.preferredHeight: 58
                radius: 10
                color: ThemeService.alpha(ThemeService.orange, 0.08)
                border.width: 1
                border.color: ThemeService.alpha(ThemeService.orange, 0.30)

                RowLayout {
                    anchors.fill: parent
                    anchors.leftMargin: 14
                    anchors.rightMargin: 14
                    spacing: 12

                    Text {
                        text: "\uf06a"     // fa-exclamation-circle
                        font.family: Theme.monoFont
                        font.pixelSize: 18
                        color: ThemeService.orange
                    }
                    ColumnLayout {
                        Layout.fillWidth: true
                        spacing: 2
                        Text {
                            text: "Custom animations detected"
                            font.family: Theme.fontFamily
                            font.pixelSize: 13
                            font.weight: Font.DemiBold
                            color: ThemeService.fg
                        }
                        Text {
                            text: "~/.config/hypr/modules/animations.conf doesn't match any bundled preset. Select a preset to overwrite."
                            font.family: Theme.fontFamily
                            font.pixelSize: 11
                            color: ThemeService.grey1
                            wrapMode: Text.WordWrap
                            Layout.fillWidth: true
                        }
                    }
                                        ZenButton {
                        text: "Restore default"
                        onClicked: root.applyPreset("Default (Current)")
                    }
                }
            }

            SettingsSection {
                title: "Preset"

                SettingRow {
                    label: "Select Preset"
                    description: "Writes to ~/.config/hypr/modules/animations.conf + hyprctl reload"

                    // v6.16.4.12.6.14: Migrated to ZenDropdown for the modern
                    // Justinmind-style look (fade-on-hover, search bar at 6+
                    // items, smooth open/close).
                    //
                    // Wala tayo babawasan: ZenComboBox.qml itself is untouched;
                    // pages that haven't migrated still use it. Only this one
                    // page was changed in this version. All preset behavior
                    // (Custom external edit detection, applyPreset wiring) is
                    // preserved byte-for-byte. The model now uses the rich
                    // entry shape so we can mark "Custom (External Edit)" with
                    // a meta hint, but the values still round-trip through
                    // root.applyPreset() unchanged.
                    ZenDropdown {
                        id: presetCombo
                        width: 220
                        model: {
                            const out = []
                            const list = root.displayPresetNames || []
                            for (var i = 0; i < list.length; i++) {
                                const name = list[i]
                                if (name === "Custom (External Edit)") {
                                    out.push({
                                        text: name,
                                        value: name,
                                        meta: "external",
                                        // Greyed but selectable so user can
                                        // see why it's there. Not enabled-false
                                        // because we still want the row
                                        // focusable to convey the state.
                                        enabled: true
                                    })
                                } else {
                                    out.push({ text: name, value: name })
                                }
                            }
                            return out
                        }
                        currentIndex: {
                            const list = root.displayPresetNames || []
                            const idx = list.indexOf(root.currentPreset)
                            return idx >= 0 ? idx : 0
                        }
                        onSelected: (entry) => {
                            const name = entry.value
                            // "Custom (External Edit)" is a synthetic entry;
                            // selecting it re-applies itself (no-op) rather
                            // than calling applyPreset() which would fail
                            // the presets[] lookup.
                            if (name === "Custom (External Edit)") return
                            root.applyPreset(name)
                        }
                    }
                }
            }

            SettingsSection {
                title: "Preview"

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 280
                    color: ThemeService.alpha(ThemeService.bg0, 0.8)
                    radius: 8
                    border.width: 1
                    border.color: ThemeService.alpha(ThemeService.fg, 0.1)
                    clip: true

                    Flickable {
                        anchors.fill: parent
                        anchors.margins: 12
                        contentWidth: previewText.implicitWidth
                        contentHeight: previewText.implicitHeight
                        clip: true

                        Text {
                            id: previewText
                            // v6.16.3.4.3: when externalEdit is true, show the
                            // actual live-conf text (read-only). Otherwise, show
                            // the selected preset from the dict.
                            text: root.externalEdit
                                  ? (root.externalEditContent || "")
                                  : (root.presets[root.currentPreset] || "")
                            font.family: Theme.monoFont
                            font.pixelSize: 11
                            color: ThemeService.grey0
                        }
                    }
                }
            }

            PageFooter {
                description: "Applies instantly via hyprctl reload"
                onResetRequested: root.applyPreset("Default (Current)")
            }

            // v6.16.3.4.3: bottom breathing room — combined with the wrapper
            // Item's implicitHeight this guarantees the PageFooter is fully
            // scrollable into view.
            Item { Layout.preferredHeight: 24 }
        }
    }
}
