"""
═══════════════════════════════════════════════════════════════════════════════
THEME APPLIERS - Apply themes to Waybar, Rofi, Kitty, Control Center
═══════════════════════════════════════════════════════════════════════════════
"""

import subprocess
from pathlib import Path
from typing import Dict

from .constants import (
    WAYBAR_DIR, WAYBAR_COLORSCHEME_DIR, WAYBAR_STYLE_FILE,
    ROFI_DIR, KITTY_DIR, ASSETS_DIR,
    DEFAULT_WAYBAR_STYLE, FONT_FAMILIES
)


class ThemeApplier:
    """Apply themes to various applications"""
    
    # ═══════════════════════════════════════════════════════════════════════
    # WAYBAR COLORSCHEME
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def apply_waybar_colorscheme(theme_data: Dict) -> bool:
        """Generate Waybar colorscheme CSS file with @define-color variables"""
        colors = theme_data.get("colors", {})
        theme_id = theme_data.get("id", "custom")
        
        css = f"""/* Auto-generated by Hyprland Control Center */
/* Theme: {theme_data.get('name', 'Custom')} */

@define-color bg0 {colors.get('bg0', '#282c34')};
@define-color bg1 {colors.get('bg1', '#21252b')};
@define-color bg2 {colors.get('bg2', '#2c313a')};
@define-color bg3 {colors.get('bg3', '#3e4451')};
@define-color bg4 {colors.get('bg4', '#4b5263')};

@define-color fg {colors.get('fg', '#abb2bf')};
@define-color grey0 {colors.get('grey0', '#5c6370')};
@define-color grey1 {colors.get('grey1', '#828997')};
@define-color grey2 {colors.get('grey2', '#abb2bf')};

@define-color red {colors.get('red', '#e06c75')};
@define-color orange {colors.get('orange', '#d19a66')};
@define-color yellow {colors.get('yellow', '#e5c07b')};
@define-color green {colors.get('green', '#98c379')};
@define-color aqua {colors.get('aqua', '#56b6c2')};
@define-color blue {colors.get('blue', '#61afef')};
@define-color purple {colors.get('purple', '#c678dd')};
"""
        
        WAYBAR_COLORSCHEME_DIR.mkdir(parents=True, exist_ok=True)
        css_file = WAYBAR_COLORSCHEME_DIR / f"{theme_id}.css"
        with open(css_file, 'w') as f:
            f.write(css)
        
        # Update style.css @import
        style_file = WAYBAR_DIR / "style.css"
        if style_file.exists():
            with open(style_file) as f:
                content = f.read()
            
            if "@import" in content:
                lines = content.split('\n')
                for i, line in enumerate(lines):
                    if "@import" in line and "colorscheme" in line:
                        lines[i] = f"@import '../hypr/colorscheme/{theme_id}.css';"
                        break
                with open(style_file, 'w') as f:
                    f.write('\n'.join(lines))
        
        return True
    
    # ═══════════════════════════════════════════════════════════════════════
    # WAYBAR STYLE (Detailed CSS)
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def apply_waybar_style(theme_data: Dict) -> bool:
        """Apply detailed Waybar styling from waybar_style config"""
        waybar_style = theme_data.get("waybar_style", DEFAULT_WAYBAR_STYLE)
        waybar_config = theme_data.get("waybar", {})
        
        # Generate waybar-theming.css
        css = ThemeApplier._generate_waybar_style_css(waybar_style, waybar_config)
        
        # Save to assets
        ASSETS_DIR.mkdir(parents=True, exist_ok=True)
        style_file = ASSETS_DIR / "waybar-theming.css"
        with open(style_file, 'w') as f:
            f.write(css)
        
        return True
    
    @staticmethod
    def _generate_waybar_style_css(style: Dict, config: Dict) -> str:
        """Generate Waybar theming CSS"""
        window = style.get("window", {})
        ws = style.get("workspaces", {})
        ws_btn = style.get("workspaces_button", {})
        ws_active = style.get("workspaces_button_active", {})
        ws_hover = style.get("workspaces_button_hover", {})
        ws_urgent = style.get("workspaces_button_urgent", {})
        modules = style.get("modules", {})
        taskbar = style.get("taskbar", {})
        taskbar_btn = style.get("taskbar_button", {})
        font = style.get("font", {})
        
        # Get color mappings from config
        ws_cfg = config.get("workspaces", {})
        
        css = f"""/* ═══════════════════════════════════════════════════════════════ */
/* WAYBAR THEMING - Auto-generated by Hyprland Control Center       */
/* ═══════════════════════════════════════════════════════════════ */

/* Global Font */
* {{
    font-family: "{font.get('family', 'JetBrainsMono Nerd Font Propo')}", sans-serif;
    font-size: {font.get('size', 14)}px;
}}

/* Main Window */
window#waybar {{
    border-radius: {window.get('border_radius', 0)}px;
    background: alpha(@bg0, {window.get('background_opacity', 0.50)});
}}

/* Workspaces Container */
#workspaces {{
    background-color: alpha(@bg0, {ws.get('background_opacity', 0.21)});
    padding: {ws.get('padding', '5px 3px 5px 3px')};
    min-width: {ws.get('min_width', 176)}px;
    margin: {ws.get('margin', '0 0 0 12px')};
    border-radius: {ws.get('border_radius', 26)}px;
    border: 1px solid @bg1;
    color: @fg;
}}

/* Workspace Buttons - Normal */
#workspaces button {{
    padding: {ws_btn.get('padding', '0px 6px')};
    margin: {ws_btn.get('margin', '0px 3px')};
    color: transparent;
    border-radius: {ws_btn.get('border_radius', 16)}px;
    background-color: @{ws_cfg.get('button_normal_bg', 'bg1')};
    transition: all 0.3s ease-in-out;
}}

/* Workspace Buttons - Active */
#workspaces button.active {{
    background-color: @{ws_cfg.get('button_active_bg', 'blue')};
    color: @{ws_cfg.get('button_active_text', 'bg0')};
    min-width: {ws_active.get('min_width', 50)}px;
    border-radius: {ws_active.get('border_radius', 16)}px;
    transition: all 0.3s ease-in-out;
    font-size: {ws_active.get('font_size', 13)}px;
}}

/* Workspace Buttons - Hover */
#workspaces button:hover {{
    background-color: @{ws_cfg.get('button_hover_bg', 'purple')};
    color: @{ws_cfg.get('button_hover_text', 'bg0')};
    border-radius: {ws_hover.get('border_radius', 16)}px;
    min-width: {ws_hover.get('min_width', 50)}px;
    background-size: 400% 400%;
}}

/* Workspace Buttons - Urgent */
#workspaces button.urgent {{
    background-color: @{ws_cfg.get('button_urgent_bg', 'red')};
    color: @{ws_cfg.get('button_urgent_text', 'bg0')};
    border-radius: {ws_urgent.get('border_radius', 16)}px;
    min-width: {ws_urgent.get('min_width', 50)}px;
    background-size: 400% 400%;
    transition: all 0.3s ease-in-out;
}}

/* System Modules Base */
#battery,
#pulseaudio,
#cpu,
#memory,
#temperature,
#network,
#bluetooth,
#clock,
#custom-notification {{
    background-color: alpha(@bg0, 0.9);
    padding: {modules.get('padding', '0 15px')};
    margin: {modules.get('margin', '0 0 0 12px')};
    border-radius: {modules.get('border_radius', 45)}px;
    border: 1px solid @bg1;
    transition: all 0.25s ease-in-out;
}}

/* Taskbar Container */
#taskbar {{
    background-color: @bg0;
    padding: {taskbar.get('padding', '5px 6px')};
    margin: {taskbar.get('margin', '0 0 0 12px')};
    border-radius: {taskbar.get('border_radius', 18)}px;
    border: 1px solid @bg1;
}}

/* Taskbar Buttons */
#taskbar button {{
    padding: {taskbar_btn.get('padding', '0.4em 0.8em')};
    margin: {taskbar_btn.get('margin', '0 4px')};
    border-radius: {taskbar_btn.get('border_radius', 14)}px;
    background-color: @bg1;
    color: @fg;
    transition: all 0.25s ease-in-out;
}}

#taskbar button.active {{
    background-color: @blue;
    color: @bg0;
}}

#taskbar button:hover {{
    background-color: @bg3;
    color: @fg;
}}
"""
        return css
    
    # ═══════════════════════════════════════════════════════════════════════
    # ROFI
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def apply_rofi_colors(theme_data: Dict) -> bool:
        """Generate Rofi colors.rasi file"""
        rofi = theme_data.get("rofi", {})
        colors = theme_data.get("colors", {})
        
        def ensure_alpha(color):
            if len(color) == 7:
                return color + "FF"
            return color
        
        content = f"""/**
 * Auto-generated by Hyprland Control Center
 * Theme: {theme_data.get('name', 'Custom')}
 **/

* {{
    background:     {ensure_alpha(rofi.get('background', colors.get('bg0', '#282c34')))};
    background-alt: {ensure_alpha(rofi.get('background-alt', colors.get('bg1', '#21252b')))};
    foreground:     {ensure_alpha(rofi.get('foreground', colors.get('fg', '#abb2bf')))};
    selected:       {ensure_alpha(rofi.get('selected', colors.get('blue', '#61afef')))};
    active:         {ensure_alpha(rofi.get('active', colors.get('green', '#98c379')))};
    urgent:         {ensure_alpha(rofi.get('urgent', colors.get('red', '#e06c75')))};
}}
"""
        
        rofi_shared = ROFI_DIR / "shared"
        rofi_shared.mkdir(parents=True, exist_ok=True)
        with open(rofi_shared / "colors.rasi", 'w') as f:
            f.write(content)
        
        return True
    
    # ═══════════════════════════════════════════════════════════════════════
    # KITTY
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def apply_kitty_colors(theme_data: Dict) -> bool:
        """Generate Kitty theme.conf file"""
        kitty = theme_data.get("kitty", {})
        colors = theme_data.get("colors", {})
        
        content = f"""# Auto-generated by Hyprland Control Center
# Theme: {theme_data.get('name', 'Custom')}

background  {kitty.get('background', colors.get('bg0', '#282c34'))}
foreground  {kitty.get('foreground', colors.get('fg', '#abb2bf'))}
cursor      {kitty.get('cursor', colors.get('blue', '#61afef'))}

# black
color0  {kitty.get('color0', colors.get('bg0', '#282c34'))}
color8  {kitty.get('color8', colors.get('grey0', '#5c6370'))}

# red
color1  {kitty.get('color1', colors.get('red', '#e06c75'))}
color9  {kitty.get('color9', colors.get('red', '#e06c75'))}

# green
color2   {kitty.get('color2', colors.get('green', '#98c379'))}
color10  {kitty.get('color10', colors.get('green', '#98c379'))}

# yellow
color3   {kitty.get('color3', colors.get('yellow', '#e5c07b'))}
color11  {kitty.get('color11', colors.get('yellow', '#e5c07b'))}

# blue
color4   {kitty.get('color4', colors.get('blue', '#61afef'))}
color12  {kitty.get('color12', colors.get('blue', '#61afef'))}

# magenta
color5   {kitty.get('color5', colors.get('purple', '#c678dd'))}
color13  {kitty.get('color13', colors.get('purple', '#c678dd'))}

# cyan
color6   {kitty.get('color6', colors.get('aqua', '#56b6c2'))}
color14  {kitty.get('color14', colors.get('aqua', '#56b6c2'))}

# white
color7   {kitty.get('color7', colors.get('fg', '#abb2bf'))}
color15  {kitty.get('color15', colors.get('grey0', '#5c6370'))}
"""
        
        KITTY_DIR.mkdir(parents=True, exist_ok=True)
        with open(KITTY_DIR / "theme.conf", 'w') as f:
            f.write(content)
        
        return True
    
    # ═══════════════════════════════════════════════════════════════════════
    # CONTROL CENTER CSS
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def apply_control_center_theme(theme_data: Dict) -> str:
        """Generate Control Center CSS with theme colors"""
        colors = theme_data.get("colors", {})
        
        css = f"""/* Auto-generated theme CSS */
:root {{
    --bg0: {colors.get('bg0', '#282c34')};
    --bg1: {colors.get('bg1', '#21252b')};
    --bg2: {colors.get('bg2', '#2c313a')};
    --bg3: {colors.get('bg3', '#3e4451')};
    --bg4: {colors.get('bg4', '#4b5263')};
    --fg: {colors.get('fg', '#abb2bf')};
    --grey0: {colors.get('grey0', '#5c6370')};
    --grey1: {colors.get('grey1', '#828997')};
    --grey2: {colors.get('grey2', '#abb2bf')};
    --red: {colors.get('red', '#e06c75')};
    --orange: {colors.get('orange', '#d19a66')};
    --yellow: {colors.get('yellow', '#e5c07b')};
    --green: {colors.get('green', '#98c379')};
    --aqua: {colors.get('aqua', '#56b6c2')};
    --blue: {colors.get('blue', '#61afef')};
    --purple: {colors.get('purple', '#c678dd')};
}}
"""
        return css
    
    # ═══════════════════════════════════════════════════════════════════════
    # RELOAD HELPERS
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def reload_waybar():
        """Reload Waybar to apply changes"""
        try:
            subprocess.run(["pkill", "-SIGUSR2", "waybar"], check=False)
            return True
        except:
            return False
    
    @staticmethod
    def reload_kitty():
        """Reload Kitty to apply changes"""
        try:
            subprocess.run(["pkill", "-USR1", "kitty"], check=False)
            return True
        except:
            return False
    
    @staticmethod
    def notify(title: str, message: str, icon: str = "preferences-desktop-theme"):
        """Send desktop notification"""
        try:
            subprocess.run([
                "notify-send", 
                "-a", "Hyprland Control Center",
                "-i", icon,
                title, message
            ], check=False)
        except:
            pass
    
    # ═══════════════════════════════════════════════════════════════════════
    # APPLY ALL
    # ═══════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def apply_all(theme_data: Dict, include_control_center: bool = True) -> Dict[str, bool]:
        """Apply theme to all applications"""
        results = {}
        
        # Waybar colorscheme
        results["waybar_colors"] = ThemeApplier.apply_waybar_colorscheme(theme_data)
        
        # Waybar detailed styling
        results["waybar_style"] = ThemeApplier.apply_waybar_style(theme_data)
        
        # Rofi
        results["rofi"] = ThemeApplier.apply_rofi_colors(theme_data)
        
        # Kitty
        results["kitty"] = ThemeApplier.apply_kitty_colors(theme_data)
        
        # Reload apps
        if results["waybar_colors"] or results["waybar_style"]:
            ThemeApplier.reload_waybar()
        
        if results["kitty"]:
            ThemeApplier.reload_kitty()
        
        return results
