[general]
framerate = 30
bars = 50
autosens = 1
sensitivity = 150

[input]
method = pulse
source = auto

[output]
method = raw
data_format = ascii
ascii_max_range = 7
bar_delimiter = 59

[smoothing]
monstercat = 1
waves = 0
noise_reduction = 66
