#!/usr/bin/env bash
# zen-panasonic-setup — Panasonic Let's Note support for Zen Shell
#   v8.0.0-alpha-hf179 · Karui (軽い)
#
# Detects a Let's Note, then sets up:
#   1. the round-touchpad Hyprland tuning (edge scroll — works with zero code)
#   2. the zen-wheelpad daemon (true circular scroll — needs uinput access)
#   3. panasonic-laptop module bindings (ECO battery limit, sticky keys)
#
# Everything is idempotent and everything is opt-in. Run with --dry-run first.
#
# Wala tayong babawasan — this only ADDS files. It never edits hyprland.conf
# in place; it drops a sourceable snippet and tells you the one line to add.

set -uo pipefail

DRY=0
FORCE=0
for a in "$@"; do
    case "$a" in
        --dry-run) DRY=1 ;;
        --force)   FORCE=1 ;;
        -h|--help)
            echo "usage: zen-panasonic-setup [--dry-run] [--force]"
            echo "  --dry-run  show what would happen, change nothing"
            echo "  --force    proceed even if this is not a Panasonic"
            exit 0 ;;
    esac
done

say()  { printf '  %s\n' "$*"; }
head_() { printf '\n\033[1m%s\033[0m\n' "$*"; }
run()  { if [ "$DRY" = 1 ]; then say "would: $*"; else eval "$@"; fi }

dmi() { cat "/sys/class/dmi/id/$1" 2>/dev/null | tr -d '\0'; }

# $USER is not exported by every login path, and `set -u` makes that fatal.
WHO="${USER:-${LOGNAME:-$(id -un)}}"

VENDOR="$(dmi sys_vendor)"
PRODUCT="$(dmi product_name)"
FAMILY="$(dmi product_family)"

head_ "Zen Shell — Panasonic Let's Note support"
say "vendor:  ${VENDOR:-unknown}"
say "product: ${PRODUCT:-unknown}"
say "family:  ${FAMILY:-unknown}"

IS_PANA=0
case "${VENDOR,,}" in
    *panasonic*|*matsushita*) IS_PANA=1 ;;
esac
case "${PRODUCT^^}" in
    CF-*|FZ-*) IS_PANA=1 ;;
esac

if [ "$IS_PANA" = 0 ] && [ "$FORCE" = 0 ]; then
    say ""
    say "This does not look like a Panasonic. Nothing to do."
    say "Run with --force if you have a round touchpad anyway."
    exit 0
fi
[ "$IS_PANA" = 1 ] && say "→ Let's Note detected."

# v8.0.0-alpha-hf186 — --force also persists the page override, so the
# Panasonic settings page appears in the Control Center on this machine.
# Separate from the daemon's own DMI check: the page becomes reachable, the
# daemon still refuses to grab a touchpad it has no business grabbing.
if [ "$IS_PANA" = 0 ] && [ "$FORCE" = 1 ] && [ "$DRY" = 0 ]; then
    CFG="$HOME/.config/zen-shell/wheelpad.json"
    mkdir -p "$(dirname "$CFG")"
    if [ -f "$CFG" ] && command -v python3 >/dev/null 2>&1; then
        python3 - "$CFG" <<'PYFORCE'
import json, sys
p = sys.argv[1]
try:
    with open(p) as fh: cfg = json.load(fh)
except Exception:
    cfg = {}
cfg["force_page"] = True
with open(p, "w") as fh: json.dump(cfg, fh, indent=2)
PYFORCE
    else
        printf '{\n  "force_page": true\n}\n' > "$CFG"
    fi
    say "→ --force: wrote force_page to $CFG"
    say "  The Panasonic page will now show in the Control Center on this box."
    say "  For one session without persisting: ZEN_PANASONIC_FORCE=1 quickshell"
fi

# ── Which touchpad ──────────────────────────────────────────────────────────
head_ "1. Touchpad"
TP_NAME="$(
  for d in /sys/class/input/event*/device/name; do
    n="$(cat "$d" 2>/dev/null)"
    case "${n,,}" in *touchpad*|*trackpad*) echo "$n"; break ;; esac
  done
)"
if [ -n "$TP_NAME" ]; then
    say "found: $TP_NAME"
else
    say "no touchpad name matched — the daemon auto-detects by capability,"
    say "so this is not fatal. \`hyprctl devices\` will show the real name."
fi

# Hyprland wants the lowercased, space-to-dash form for device blocks.
TP_HYPR="$(echo "${TP_NAME:-}" | tr '[:upper:] ' '[:lower:]-')"

# ── Hyprland snippet ────────────────────────────────────────────────────────
head_ "2. Hyprland tuning for a small round pad"
HYPR_DIR="$HOME/.config/hypr"
SNIPPET="$HYPR_DIR/zen-panasonic.conf"

say "writing $SNIPPET"
if [ "$DRY" = 0 ]; then
    mkdir -p "$HYPR_DIR"
    cat > "$SNIPPET" <<EOF
# ═══════════════════════════════════════════════════════════════════
# Zen Shell — Panasonic Let's Note touchpad tuning
# Generated by zen-panasonic-setup on $(date -Iseconds)
# Model: ${PRODUCT:-unknown}
#
# Source this from hyprland.conf:
#     source = ~/.config/hypr/zen-panasonic.conf
# ═══════════════════════════════════════════════════════════════════

input {
    # ── Edge scrolling ──
    # libinput has no circular scroll (see the CF-SV9 ArchWiki page), but a
    # round pad's outer ring IS its right edge, so edge scrolling gets you
    # most of the wheel-pad feel with zero extra software. This is the
    # fallback if you do not want to run the zen-wheelpad daemon.
    #
    # NOTE: this belongs in input{}, NOT in input:touchpad{} — putting it in
    # the touchpad block silently does nothing.
    scroll_method = edge

    # The pad is ~40mm across. Default accel makes it take three swipes to
    # cross a 1920x1200 screen; a little positive sensitivity fixes that
    # without making it twitchy.
    sensitivity = 0.25
    accel_profile = adaptive

    touchpad {
        natural_scroll = false
        tap-to-click = true
        # Two-finger anything is cramped on a pad this size — clickfinger
        # gives you right-click from a two-finger tap without needing to
        # aim at a software button zone that is barely 12mm wide.
        clickfinger_behavior = true
        disable_while_typing = true
        drag_lock = true
        # Edge scroll on a small pad delivers a lot of events per mm.
        scroll_factor = 0.6
    }
}
EOF
fi

if [ -n "$TP_HYPR" ] && [ "$DRY" = 0 ]; then
    cat >> "$SNIPPET" <<EOF

# Per-device block, in case you attach an external mouse and want the
# tuning above to apply only to the built-in pad.
# device {
#     name = $TP_HYPR
#     sensitivity = 0.25
# }
EOF
fi

say ""
say "Add this ONE line to ~/.config/hypr/hyprland.conf if it is not there:"
say "    source = ~/.config/hypr/zen-panasonic.conf"

# ── uinput access for the daemon ────────────────────────────────────────────
head_ "3. zen-wheelpad (true circular scroll)"

if ! python3 -c "import evdev" 2>/dev/null; then
    say "python-evdev is NOT installed. The daemon needs it:"
    say "    sudo pacman -S python-evdev"
    say "(edge scrolling above works without it)"
fi

UDEV_RULE=/etc/udev/rules.d/99-zen-wheelpad.rules
say "udev rule: $UDEV_RULE  (needs root)"
if [ "$DRY" = 0 ]; then
    if [ -w /etc/udev/rules.d ] || [ "$(id -u)" = 0 ]; then
        cat > "$UDEV_RULE" <<'EOF'
# Zen Shell — let members of group `input` open /dev/uinput so zen-wheelpad
# can publish its virtual touchpad without running as root.
KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
EOF
        udevadm control --reload-rules 2>/dev/null
        say "installed."
    else
        say "not root — run this by hand:"
        say "    sudo tee $UDEV_RULE >/dev/null <<'EOF'"
        say "    KERNEL==\"uinput\", GROUP=\"input\", MODE=\"0660\", OPTIONS+=\"static_node=uinput\""
        say "    EOF"
        say "    sudo udevadm control --reload-rules"
    fi
fi

if ! id -nG "$WHO" | tr ' ' '\n' | grep -qx input; then
    say ""
    say "You are NOT in the 'input' group. The daemon cannot read the pad."
    say "    sudo usermod -aG input $WHO      # then log out and back in"
fi

# ── systemd user service ────────────────────────────────────────────────────
SVC_DIR="$HOME/.config/systemd/user"
SVC="$SVC_DIR/zen-wheelpad.service"
DAEMON="$HOME/.config/quickshell/zen-shell/scripts/zen-wheelpad.py"
[ -f "$DAEMON" ] || DAEMON="$HOME/.local/bin/zen-wheelpad.py"

say ""
say "systemd user unit: $SVC"
if [ "$DRY" = 0 ]; then
    mkdir -p "$SVC_DIR"
    cat > "$SVC" <<EOF
[Unit]
Description=Zen Shell — circular scrolling for Panasonic Let's Note touchpads
Documentation=https://github.com/Gekinzen/zen-shell
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 $DAEMON
Restart=on-failure
RestartSec=3
# If the daemon dies the kernel drops the grab by itself, so a restart loop
# can never leave the pad captured by a dead process.

[Install]
WantedBy=graphical-session.target
EOF
    systemctl --user daemon-reload 2>/dev/null
fi

# ── panasonic-laptop module ─────────────────────────────────────────────────
head_ "4. panasonic-laptop kernel module"
if lsmod 2>/dev/null | grep -q '^panasonic_laptop'; then
    say "loaded."
else
    say "not loaded — try: sudo modprobe panasonic-laptop"
    say "(gives you hotkeys, sticky keys and the ECO battery limit)"
fi

PLAT=/sys/devices/platform/panasonic
if [ -d "$PLAT" ]; then
    say "sysfs at $PLAT:"
    for f in eco_mode sticky_key cdpower ac_brightness dc_brightness current_brightness mute; do
        [ -e "$PLAT/$f" ] && say "  $f = $(cat "$PLAT/$f" 2>/dev/null)"
    done
    say ""
    say "ECO mode caps the battery at ~80% to preserve its life:"
    say "    echo 1 | sudo tee $PLAT/eco_mode    # on"
    say "    echo 0 | sudo tee $PLAT/eco_mode    # off"
    say "Note: it resets to the firmware's value on the next POST cycle."
else
    say "no $PLAT — module not loaded, or this model does not expose it."
fi

# ── Done ────────────────────────────────────────────────────────────────────
head_ "Next steps"
cat <<'EOF'
  1. source the snippet from hyprland.conf, then `hyprctl reload`
     → edge scrolling on the ring works immediately, no daemon needed

  2. try the daemon SAFELY first — it does not grab anything in dry-run:
       python3 zen-wheelpad.py --list
       python3 zen-wheelpad.py --dry-run
     circle the outer ring; you should see engage/scroll lines print.

  3. happy with it?
       systemctl --user enable --now zen-wheelpad

  4. tune it in Zen Control Center → Panasonic, or in
     ~/.config/zen-shell/wheelpad.json

  If anything feels wrong:  systemctl --user stop zen-wheelpad
  The kernel releases the grab instantly and the pad behaves as stock.
EOF
