#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
# zen-boost-guard — v8.1.0-alpha-hf200
#
# "Use dynamic compression/limiting at around 80% intensity while
#  allowing up to 3.0x gain, so the volume can reach 300% amplification
#  without excessive clipping or distortion."
#
# ── WHY ───────────────────────────────────────────────────────────────
# wpctl set-volume 3.0 is applied by PipeWire as the LAST stage before
# the float→int conversion at the ALSA boundary. Nothing sits after it,
# so anything past 0 dBFS hard-clips at the DAC — that's the harsh
# distortion at 173%+. A limiter can't be inserted inside the device
# sink's own adapter, so the fix is a GUARD SINK in front of it:
#
#   apps ──▶ [Zen Boost 保護 sink]  ← your 0–300% volume lands HERE,
#             │                        PRE-chain (sink volume is applied
#             │                        on the adapter input)
#             ├─ SC4 compressor      ← ~80% intensity: tames the peaks,
#             │                        adds makeup loudness
#             ├─ fast lookahead      ← brick wall at -1 dBFS: whatever
#             │  limiter                survives the compressor cannot
#             │                        clip the DAC
#             └──▶ real device sink  (pinned at 100%)
#
# So the shell's existing volume plumbing (wpctl @DEFAULT_AUDIO_SINK@,
# hf197–hf199) is UNTOUCHED — the default sink is simply the guard, and
# "300%" now means "3.0x into a compressor+limiter" instead of "3.0x
# into a brick wall".
#
# ── QUALITY LADDER ────────────────────────────────────────────────────
#   ladspa   : SC4 (sc4_1882) + Fast Lookahead Limiter (…_1913) from
#              swh-plugins — the real thing.  pacman -S swh-plugins
#   clamp    : swh-plugins missing → builtin soft path: gain still lands
#              pre-chain and a hard clamp at ±1 keeps the DAC honest.
#              Same loudness, more edge — install swh-plugins, pre.
#
# ── USAGE ─────────────────────────────────────────────────────────────
#   zen-boost-guard.sh start [target-sink-name]
#   zen-boost-guard.sh stop
#   zen-boost-guard.sh status        → ACTIVE|INACTIVE / TARGET=… / QUALITY=…
#   zen-boost-guard.sh set-target <sink-name>   (restart with new device)
#
# Tunables (env):
#   ZEN_BOOST_INTENSITY   0..1, default 0.80  — compressor drive
#   ZEN_BOOST_LIMIT_DB    default -1.0        — limiter ceiling
#
# Wala tayong babawasan — purely additive; stop returns the plain path.
# ═══════════════════════════════════════════════════════════════════════

set -u

CACHE="$HOME/.cache/zen-shell"
STATE="$CACHE/boost-guard.state"        # TARGET=… QUALITY=… PID=…
CONF="$CACHE/zen-boost-chain.conf"
LOG="$CACHE/boost-guard.log"
SINK_NAME="zen_boost_sink"
SINK_DESC="Zen Boost 保護"

INTENSITY="${ZEN_BOOST_INTENSITY:-0.80}"
LIMIT_DB="${ZEN_BOOST_LIMIT_DB:--1.0}"

mkdir -p "$CACHE"
log() { echo "[$(date +%H:%M:%S)] $*" >> "$LOG"; }

# ── intensity → SC4 params (his "~80%") ───────────────────────────────
# threshold  -6 … -20 dB   (harder squeeze as intensity rises)
# ratio       1 … 8 : 1
# makeup      0 … 6 dB     (the compressor GIVES BACK loudness — this is
#                           what makes 300% actually sound louder instead
#                           of just clipping harder)
calc() { awk "BEGIN{printf \"%.2f\", $1}"; }
THRESH=$(calc "-6 - 14 * $INTENSITY")
RATIO=$(calc  "1 + 7 * $INTENSITY")
MAKEUP=$(calc "6 * $INTENSITY")

have_ladspa() {
    local d
    for d in /usr/lib/ladspa /usr/lib64/ladspa /usr/local/lib/ladspa "$HOME/.ladspa"; do
        [ -f "$d/sc4_1882.so" ] && [ -f "$d/fast_lookahead_limiter_1913.so" ] && return 0
    done
    return 1
}

default_hw_sink() {
    # The current default sink's node.name — used as the target when
    # `start` is called without one. If the default is already the guard
    # (restart case), fall back to the state file's TARGET.
    local n
    n=$(pw-metadata -n settings 0 default.audio.sink 2>/dev/null \
        | grep -oP '"name":"\K[^"]+' | head -1)
    if [ "$n" = "$SINK_NAME" ] || [ -z "$n" ]; then
        n=$(grep -oP '^TARGET=\K.*' "$STATE" 2>/dev/null | head -1)
    fi
    echo "$n"
}

write_conf() {
    local target="$1" quality="$2"
    if [ "$quality" = "ladspa" ]; then
        cat > "$CONF" << EOF
# generated by zen-boost-guard (hf200) — do not edit, regenerated on start
context.properties = { log.level = 2 }
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "$SINK_DESC"
      media.name       = "$SINK_DESC"
      filter.graph = {
        nodes = [
          { type = ladspa plugin = sc4_1882 label = sc4 name = comp
            control = { "RMS/peak" = 0.2 "Attack time (ms)" = 3.0
                        "Release time (ms)" = 150.0
                        "Threshold level (dB)" = $THRESH
                        "Ratio (1:n)" = $RATIO
                        "Knee radius (dB)" = 6.0
                        "Makeup gain (dB)" = $MAKEUP } }
          { type = ladspa plugin = fast_lookahead_limiter_1913
            label = fastLookaheadLimiter name = lim
            control = { "Input gain (dB)" = 0.0
                        "Limit (dB)" = $LIMIT_DB
                        "Release time (s)" = 0.15 } }
        ]
        links = [
          { output = "comp:Left output"  input = "lim:Input 1" }
          { output = "comp:Right output" input = "lim:Input 2" }
        ]
        inputs  = [ "comp:Left input" "comp:Right input" ]
        outputs = [ "lim:Output 1" "lim:Output 2" ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name   = "$SINK_NAME"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name        = "zen_boost_out"
        node.passive     = true
        node.target      = "$target"
        node.dont-reconnect = true
      }
    }
  }
]
EOF
    else
        # builtin fallback: hard clamp at ±1 per channel. Not pretty, but
        # deterministic — and the gain still lands pre-chain.
        cat > "$CONF" << EOF
# generated by zen-boost-guard (hf200) — builtin fallback (install swh-plugins!)
context.properties = { log.level = 2 }
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "$SINK_DESC"
      media.name       = "$SINK_DESC"
      filter.graph = {
        nodes = [
          { type = builtin label = clamp name = clampL control = { "Min" = -1.0 "Max" = 1.0 } }
          { type = builtin label = clamp name = clampR control = { "Min" = -1.0 "Max" = 1.0 } }
        ]
        inputs  = [ "clampL:In"  "clampR:In" ]
        outputs = [ "clampL:Out" "clampR:Out" ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name   = "$SINK_NAME"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name        = "zen_boost_out"
        node.passive     = true
        node.target      = "$target"
        node.dont-reconnect = true
      }
    }
  }
]
EOF
    fi
}

guard_pid() {
    grep -oP '^PID=\K[0-9]+' "$STATE" 2>/dev/null | head -1
}

is_running() {
    local p; p=$(guard_pid)
    [ -n "$p" ] && kill -0 "$p" 2>/dev/null
}

do_start() {
    local target="${1:-}"
    [ -z "$target" ] && target="$(default_hw_sink)"
    if [ -z "$target" ]; then
        log "start: no target sink resolvable"; echo "ERR: no target sink"; exit 1
    fi
    if is_running; then
        log "start: already running (pid $(guard_pid))"; do_status; exit 0
    fi
    local quality="clamp"
    have_ladspa && quality="ladspa"
    write_conf "$target" "$quality"
    log "start: target=$target quality=$quality intensity=$INTENSITY thresh=$THRESH ratio=$RATIO makeup=$MAKEUP limit=$LIMIT_DB"

    nohup pipewire -c "$CONF" >> "$LOG" 2>&1 &
    local pid=$!
    # Wait for the sink node to materialize (up to 3s)
    local i ok=0
    for i in $(seq 1 30); do
        pw-cli ls Node 2>/dev/null | grep -q "$SINK_NAME" && { ok=1; break; }
        sleep 0.1
    done
    if [ "$ok" != "1" ]; then
        log "start: sink never appeared — killing $pid"; kill "$pid" 2>/dev/null
        echo "ERR: guard sink failed to start (see $LOG)"; exit 1
    fi

    # Pin the REAL device at 100% — the guard owns all gain from here.
    wpctl status >/dev/null 2>&1 && {
        local tid
        tid=$(pw-cli ls Node 2>/dev/null | awk -v n="node.name = \"$target\"" '
              /^\tid/ { id=$2; sub(",","",id) } $0 ~ n { print id; exit }')
        [ -n "$tid" ] && wpctl set-volume "$tid" 1.0 2>/dev/null \
            && log "start: pinned $target ($tid) at 1.0"
    }

    # Make the guard the default sink; existing streams migrate with it.
    local gid
    gid=$(pw-cli ls Node 2>/dev/null | awk -v n="node.name = \"$SINK_NAME\"" '
          /^\tid/ { id=$2; sub(",","",id) } $0 ~ n { print id; exit }')
    [ -n "$gid" ] && wpctl set-default "$gid" && log "start: default → guard ($gid)"

    {
        echo "TARGET=$target"
        echo "QUALITY=$quality"
        echo "PID=$pid"
    } > "$STATE"
    do_status
}

do_stop() {
    local target
    target=$(grep -oP '^TARGET=\K.*' "$STATE" 2>/dev/null | head -1)
    local p; p=$(guard_pid)
    [ -n "$p" ] && kill "$p" 2>/dev/null && log "stop: killed $p"
    # Hand the default back to the real device so audio keeps flowing.
    if [ -n "$target" ]; then
        local tid
        tid=$(pw-cli ls Node 2>/dev/null | awk -v n="node.name = \"$target\"" '
              /^\tid/ { id=$2; sub(",","",id) } $0 ~ n { print id; exit }')
        [ -n "$tid" ] && wpctl set-default "$tid" && log "stop: default → $target ($tid)"
    fi
    rm -f "$STATE"
    echo "INACTIVE"
}

do_status() {
    if is_running; then
        echo "ACTIVE"
        grep -E '^(TARGET|QUALITY)=' "$STATE" 2>/dev/null
    else
        echo "INACTIVE"
    fi
}

case "${1:-status}" in
    start)      do_start "${2:-}" ;;
    stop)       do_stop ;;
    status)     do_status ;;
    set-target)
        [ -z "${2:-}" ] && { echo "ERR: set-target needs a sink name"; exit 1; }
        log "set-target: $2 (restart)"
        # Brief gap (<1s) while the chain relaunches on the new device;
        # streams stay parked on the guard sink and resume automatically.
        is_running && do_stop_quiet=1
        if [ -n "${do_stop_quiet:-}" ]; then
            p=$(guard_pid); [ -n "$p" ] && kill "$p" 2>/dev/null
            rm -f "$STATE"
        fi
        do_start "$2"
        ;;
    *) echo "usage: $0 {start [target]|stop|status|set-target <sink-name>}"; exit 2 ;;
esac
