#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = swww-daemon
exec-once = waybar 
exec-once = swaync
exec-once = flameshot
# ~/.config/hypr/hyprland.conf
#exec-once = ~/.config/hypr/scripts/auto-tiling.sh monitor
#exec-once = sleep 2 && hyprpm enable hyprbars && hyprpm enable Hyprspace && hyprctl reload
echo 'exec-once = ~/.config/hypr/scripts/wallpaper-slideshow.sh' >> ~/.config/hypr/hyprland.conf


exec-once = ~/.config/hypr/scripts/start-widgets.sh
# Add to ~/.config/hypr/hyprland.conf temporarily
#exec = python3 ~/.config/hypr-control-center/src/panel/panel_widget.py
#exec-once = ~/.config/hypr-control-center/scripts/start-panel.sh start


