#!/usr/bin/env bash
# regen-swaync-theme.sh
#
# Ported from Paul's original SwayNC section (Python GTK-4 version) to bash.
# Reads ~/.config/hypr-control-center/current-theme.json and writes a
# complete SwayNC style.css to ~/.config/swaync/style.css, then reloads
# the notification daemon.
#
# Auto-called by ThemeService on every theme apply. Safe to re-run.
# Backups the previous style.css → style.css.backup on first run.
#
# Dependencies: jq, swaync (optional — skipped if not installed)

set -u

THEME_JSON="${HOME}/.config/hypr-control-center/current-theme.json"
SWAYNC_DIR="${HOME}/.config/swaync"
SWAYNC_STYLE="${SWAYNC_DIR}/style.css"
SWAYNC_BACKUP="${SWAYNC_DIR}/style.css.backup"

# ── Early exits ──
if ! command -v swaync >/dev/null 2>&1; then
    echo "[swaync] swaync not installed, skipping"
    exit 0
fi

if [ ! -f "$THEME_JSON" ]; then
    echo "[swaync] no theme at $THEME_JSON, skipping"
    exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "[swaync] jq not installed, cannot parse theme JSON"
    exit 1
fi

mkdir -p "$SWAYNC_DIR"

# ── Extract theme colors ──
hex6() {
    local raw
    raw=$(jq -r ".colors.$1 // empty" "$THEME_JSON" 2>/dev/null)
    raw="${raw#\#}"
    if [ ${#raw} -eq 8 ]; then raw="${raw:0:6}"; fi
    if [ ${#raw} -ne 6 ]; then echo "1e2127"; else echo "$raw"; fi
}

BG=$(hex6 bg0)
BG_ALT=$(hex6 bg1)
BG4=$(hex6 bg4)
FG=$(hex6 fg)
BLUE=$(hex6 blue)
RED=$(hex6 red)
THEME_NAME=$(jq -r '.name // "unknown"' "$THEME_JSON")

# Allow per-user font override via env
FONT_FAMILY="${SWAYNC_FONT:-JetBrainsMono Nerd Font}"
FONT_SIZE="${SWAYNC_FONT_SIZE:-14}"
BORDER_RADIUS="${SWAYNC_BORDER_RADIUS:-24}"
NOTIF_RADIUS="${SWAYNC_NOTIF_RADIUS:-24}"

echo "[swaync] Applying '$THEME_NAME'"
echo "  bg=#$BG  bg_alt=#$BG_ALT  fg=#$FG  accent=#$BLUE  urgent=#$RED"

# ── Backup (first run only) ──
if [ -f "$SWAYNC_STYLE" ] && [ ! -f "$SWAYNC_BACKUP" ]; then
    cp "$SWAYNC_STYLE" "$SWAYNC_BACKUP"
    echo "  ✓ backed up existing style.css → style.css.backup"
fi

# ── Generate complete style.css ──
cat > "$SWAYNC_STYLE" << CSSEOF
/* ═══════════════════════════════════════════════════════════════════════
   SwayNC Complete Theme — Auto-generated by Zen Shell v6.6
   Theme: $THEME_NAME
   Generated: $(date -Iseconds)
   DO NOT EDIT — regenerated on every theme apply via Zen Shell
   Backup: ~/.config/swaync/style.css.backup
   ═══════════════════════════════════════════════════════════════════════ */

@define-color background      #$BG;
@define-color background-alt  #$BG_ALT;
@define-color text            #$FG;
@define-color selected        #$BLUE;
@define-color hover           #$BG4;
@define-color urgent          #$RED;

* {
    color: @text;
    all: unset;
    font-size: ${FONT_SIZE}px;
    font-family: "$FONT_FAMILY", "Adwaita Sans", sans-serif;
    transition: 200ms;
}

.blank-window { background: transparent; }

/* FLOATING NOTIFICATIONS */
.notification-row { outline: none; margin: 0; padding: 0; }

.floating-notifications.background .notification-row .notification-background {
    background: alpha(@background, .55);
    box-shadow: 0 0 8px 0 rgba(0,0,0,.6);
    border: 1px solid @selected;
    border-radius: ${NOTIF_RADIUS}px;
    margin: 16px;
    padding: 0;
}

.floating-notifications.background .notification-row .notification-background .notification {
    padding: 6px;
    border-radius: 12px;
}

.floating-notifications.background .notification-row .notification-background .notification.critical {
    border: 2px solid @urgent;
}

.floating-notifications.background .notification-row .notification-background .notification .notification-content {
    margin: 14px;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * {
    min-height: 3.4em;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * .notification-action {
    border-radius: 8px;
    background-color: @background-alt;
    margin: 6px;
    border: 1px solid transparent;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * .notification-action:hover {
    background-color: @hover;
    border: 1px solid @selected;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * .notification-action:active {
    background-color: @selected;
    color: @background;
}

.image { margin: 10px 20px 10px 0; }
.summary { font-weight: 800; font-size: 1rem; }
.body { font-size: 0.8rem; }

.floating-notifications.background .notification-row .notification-background .close-button {
    margin: 6px;
    padding: 2px;
    border-radius: 6px;
    background-color: transparent;
    border: 1px solid transparent;
}

.floating-notifications.background .notification-row .notification-background .close-button:hover {
    background-color: @selected;
}

.floating-notifications.background .notification-row .notification-background .close-button:active {
    background-color: @selected;
    color: @background;
}

.notification.critical progress { background-color: @urgent; }
.notification.low progress, .notification.normal progress { background-color: @selected; }

/* CONTROL CENTER */
.control-center {
    background: @background;
    border-radius: ${BORDER_RADIUS}px;
    border: 1px solid @selected;
    box-shadow: 0 0 10px 0 rgba(0,0,0,.6);
    margin: 18px;
    padding: 12px;
}

.control-center .notification-row .notification-background,
.control-center .notification-row .notification-background .notification.critical {
    background-color: @background-alt;
    border-radius: 16px;
    margin: 4px 0;
    padding: 4px;
}

.control-center .notification-row .notification-background .notification.critical { color: @urgent; }

.control-center .notification-row .notification-background .notification .notification-content {
    margin: 6px;
    padding: 8px 6px 2px 2px;
}

.control-center .notification-row .notification-background .notification > *:last-child > * { min-height: 3.4em; }

.control-center .notification-row .notification-background .notification > *:last-child > * .notification-action {
    background: alpha(@selected, .6);
    color: @text;
    border-radius: 12px;
    margin: 6px;
}

.control-center .notification-row .notification-background .notification > *:last-child > * .notification-action:hover {
    background: @selected;
}

.control-center .notification-row .notification-background .close-button {
    background: transparent;
    border-radius: 6px;
    color: @text;
    margin: 0;
    padding: 4px;
}

.control-center .notification-row .notification-background .close-button:hover { background-color: @selected; }

progressbar, progress, trough { border-radius: 12px; }
progressbar { background-color: rgba(255,255,255,.1); }

/* NOTIFICATION GROUPS */
.notification-group { margin: 2px 8px; }
.notification-group-headers { font-weight: bold; font-size: 1.25rem; color: @text; letter-spacing: 2px; }
.notification-group-icon { color: @text; }

.notification-group-collapse-button,
.notification-group-close-all-button {
    background: transparent; color: @text; margin: 4px; border-radius: 6px; padding: 4px;
}

.notification-group-collapse-button:hover,
.notification-group-close-all-button:hover { background: @hover; }

/* WIDGETS */
.widget-title { font-size: 1.2em; margin: 6px; }
.widget-title button { background: @background-alt; border-radius: 6px; padding: 4px 16px; }
.widget-title button:hover { background-color: @hover; }
.widget-title button:active { background-color: @selected; }

.widget-dnd { margin: 6px; font-size: 1.2rem; }
.widget-dnd > switch { background: @background-alt; font-size: initial; border-radius: 8px; box-shadow: none; padding: 2px; }
.widget-dnd > switch:hover { background: @hover; }
.widget-dnd > switch:checked { background: @selected; }
.widget-dnd > switch:checked:hover { background: @hover; }
.widget-dnd > switch slider { background: @text; border-radius: 6px; }

.widget-buttons-grid { font-size: x-large; padding: 6px 2px; margin: 6px; border-radius: 12px; background: @background-alt; }
.widget-buttons-grid > flowbox > flowboxchild > button { margin: 4px 10px; padding: 6px 12px; background: transparent; border-radius: 8px; }
.widget-buttons-grid > flowbox > flowboxchild > button:hover { background: @hover; }
.widget-buttons-grid > flowbox > flowboxchild > button:active { background: @selected; }

.widget-mpris { background: @background-alt; border-radius: 16px; color: @text; margin: 20px 6px; }
.widget-mpris-player { background-color: @background; border-radius: 22px; padding: 6px 14px; margin: 6px; }
.widget-mpris > box > button { color: @text; border-radius: 20px; }
.widget-mpris button { color: alpha(@text, .6); }
.widget-mpris button:hover { color: @text; }
.widget-mpris-album-art { border-radius: 16px; }
.widget-mpris-title { font-weight: 700; font-size: 1rem; }
.widget-mpris-subtitle { font-weight: 500; font-size: 0.8rem; }

.widget-volume { background: @background; color: @text; padding: 4px; margin: 6px; border-radius: 6px; }
.widget-label { margin: 6px; }
.widget-label > label { font-size: 1rem; }

.widget-menubar > box > .menu-button-bar > button { border: none; background: transparent; }
.widget-menubar > box > .menu-button-bar > button:hover { background: @hover; }

.widget-backlight { background: @background-alt; border-radius: 12px; padding: 6px; margin: 6px; }

.widget-inhibitors { margin: 6px; font-size: 1rem; }
.widget-inhibitors > button { background: @background-alt; border-radius: 6px; padding: 4px 8px; }
.widget-inhibitors > button:hover { background: @hover; }
.widget-inhibitors > button > box > image { color: @text; }
.widget-inhibitors > button > box > label { color: @text; }
CSSEOF

echo "  ✓ wrote ${SWAYNC_STYLE}"

# ── Reload SwayNC ──
if command -v swaync-client >/dev/null 2>&1; then
    # Timeout the reload so a hung daemon doesn't block install.
    # timeout exits with 124 if it killed the process; treat it
    # as a non-fatal "daemon not responding".
    if timeout 3 swaync-client --reload-css >/dev/null 2>&1; then
        echo "  ✓ reloaded SwayNC CSS"
    else
        echo "  ⚠ swaync-client reload skipped (daemon may not be running yet)"
    fi
fi

# ── Start swaync daemon if not running ──
# CRITICAL: Must fully detach from parent shell. Otherwise even with
# nohup + & , if the parent is running under `... | sed ...`, the pipe
# stdout stays open because the daemon inherits it, and the parent
# script hangs forever waiting for the pipeline to close.
#
# Fix: setsid + redirect ALL descriptors explicitly + disown + sleep 0
# yield, so the daemon is a full session leader with no inherited file
# descriptors tying it to the installer.
if ! pgrep -x swaync >/dev/null 2>&1; then
    setsid swaync </dev/null >/dev/null 2>&1 &
    disown 2>/dev/null || true
    echo "  ✓ started swaync daemon (detached)"
fi

# Explicit exit so bash doesn't sit around waiting for children
exit 0
