#!/usr/bin/env bash
# regen-terminal-themes.sh
#
# Reads ~/.config/hypr-control-center/current-theme.json (the Zen Shell
# current theme) and regenerates:
#   ~/.config/alacritty/btm.toml      (for btm-toggle.sh)
#   ~/.config/alacritty/nmtui.toml    (for wifi-toggle.sh)
#   ~/.config/alacritty/termi.toml    (for termrun.sh)
#   ~/.config/fuzzel/fuzzel.ini       (for fuzzel launcher)
#
# Called automatically by ThemeService on every theme apply (via
# Process in ThemeService.qml). Safe to re-run manually anytime.
#
# Dependencies: jq (for JSON parsing)

set -u

THEME_JSON="${HOME}/.config/hypr-control-center/current-theme.json"
ALACRITTY_DIR="${HOME}/.config/alacritty"
FUZZEL_DIR="${HOME}/.config/fuzzel"

mkdir -p "$ALACRITTY_DIR" "$FUZZEL_DIR"

if [ ! -f "$THEME_JSON" ]; then
    echo "[regen-terminal-themes] No theme at $THEME_JSON, skipping"
    exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "[regen-terminal-themes] jq not installed, cannot parse theme JSON"
    exit 1
fi

# ── Read theme colors via jq ──
# Strip leading '#' and keep 6-hex digits.
hex6() {
    local raw
    raw=$(jq -r ".colors.$1 // empty" "$THEME_JSON" 2>/dev/null)
    raw="${raw#\#}"
    # If 8-digit hex (with alpha), strip last 2 chars
    if [ ${#raw} -eq 8 ]; then raw="${raw:0:6}"; fi
    # Default if empty / invalid
    if [ ${#raw} -ne 6 ]; then echo "1e1e2e"; else echo "$raw"; fi
}

BG0=$(hex6 bg0)
BG1=$(hex6 bg1)
BG2=$(hex6 bg2)
FG=$(hex6 fg)
GREY0=$(hex6 grey0)
GREY1=$(hex6 grey1)
GREY2=$(hex6 grey2)
RED=$(hex6 red)
ORANGE=$(hex6 orange)
YELLOW=$(hex6 yellow)
GREEN=$(hex6 green)
AQUA=$(hex6 aqua)
BLUE=$(hex6 blue)
PURPLE=$(hex6 purple)

THEME_NAME=$(jq -r '.name // "unknown"' "$THEME_JSON")

echo "[regen-terminal-themes] Applying '$THEME_NAME' to terminal configs"
echo "  bg=#$BG0 fg=#$FG"

# ── Common Alacritty color block ──
# Reused across btm.toml, nmtui.toml, termi.toml.
write_alacritty_toml() {
    local output=$1
    local window_cols=$2
    local window_lines=$3
    local padding_x=$4
    local padding_y=$5
    local font_size=$6
    local title=$7

    cat > "$output" << TOMLEOF
# Generated by regen-terminal-themes.sh
# Theme: $THEME_NAME
# DO NOT EDIT — re-run the script or apply a theme via Zen Shell

[window]
title = "$title"

[window.dimensions]
columns = $window_cols
lines = $window_lines

[window.padding]
x = $padding_x
y = $padding_y

[font]
size = $font_size

[colors.primary]
background = "#$BG0"
foreground = "#$FG"

[colors.normal]
black   = "#$BG2"
red     = "#$RED"
green   = "#$GREEN"
yellow  = "#$YELLOW"
blue    = "#$BLUE"
magenta = "#$PURPLE"
cyan    = "#$AQUA"
white   = "#$GREY0"

[colors.bright]
black   = "#$GREY1"
red     = "#$RED"
green   = "#$GREEN"
yellow  = "#$YELLOW"
blue    = "#$BLUE"
magenta = "#$PURPLE"
cyan    = "#$AQUA"
white   = "#$FG"
TOMLEOF
}

# btm.toml — CPU/temp monitor (larger window)
write_alacritty_toml "$ALACRITTY_DIR/btm.toml" 70 17 30 30 10.0 "btmWindow"

# nmtui.toml — WiFi tool (smaller)
write_alacritty_toml "$ALACRITTY_DIR/nmtui.toml" 60 20 20 20 10.0 "nmtuiWindow"

# termi.toml — general terminal (larger font)
write_alacritty_toml "$ALACRITTY_DIR/termi.toml" 70 17 1 1 15.0 "TermiWindow"

echo "  ✓ wrote alacritty/{btm,nmtui,termi}.toml"

# ── fuzzel.ini ──
cat > "$FUZZEL_DIR/fuzzel.ini" << FUZZELEOF
# Generated by regen-terminal-themes.sh
# Theme: $THEME_NAME
# DO NOT EDIT — re-run the script or apply a theme via Zen Shell

[main]
font=JetBrainsMono Nerd Font:size=11
prompt="    "
icon-theme=Papirus
icons=yes
width=40
lines=10
horizontal-pad=12
vertical-pad=10
inner-pad=8
dpi-aware=yes

[colors]
background=${BG0}ff
text=${FG}ff
match=${BLUE}ff
selection=${BG2}ff
selection-text=${FG}ff
selection-match=${YELLOW}ff
border=${BLUE}ff

[border]
width=2
radius=12
FUZZELEOF

echo "  ✓ wrote fuzzel/fuzzel.ini"

# ── Signal running instances to reload ──
# Alacritty has no live-reload for colors, so we kill any toggle-managed
# windows so their next launch picks up the new theme. The active window
# (main terminal) stays alive; user can close/reopen it manually.
pkill -f "alacritty.*btmWindow" 2>/dev/null || true
pkill -f "alacritty.*nmtuiWindow" 2>/dev/null || true

# Fuzzel reads config on every launch, nothing to signal.

echo "  ✓ theme applied to terminal configs"
