#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# zen-make-versions-lock.sh
# ═══════════════════════════════════════════════════════════════
# Snapshots the current dev-machine versions of hyprland, quickshell,
# and the Qt6 stack into <repo>/versions.lock at the repo root.
#
# Run this ONCE on the maintainer's machine right before tar-ing up
# a release. The resulting versions.lock travels in the tarball and
# is consulted by install.sh / bootstrap.sh on the user's machine.
#
# Usage:
#   ./scripts/zen-make-versions-lock.sh             # writes ../versions.lock
#   ./scripts/zen-make-versions-lock.sh --out PATH  # custom output path
#   ./scripts/zen-make-versions-lock.sh --dry-run   # print only, no write
#
# Policy:
#   - Records full version (informational) AND major.minor (enforced)
#   - Patch versions (the .X) intentionally float — Arch rolling
#     bumps patches; we don't want install.sh to whine about every
#     0.54.3 → 0.54.4 update
#   - Prefers `hyprctl version` over pacman for hyprland (catches
#     git/self-built variants); falls back to pacman -Q
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/../versions.lock"
DRY=0

while [ $# -gt 0 ]; do
    case "$1" in
        --out)     OUT="$2"; shift 2 ;;
        --dry-run) DRY=1; shift ;;
        -h|--help)
            sed -n '2,28p' "$0"
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

# ── helpers ───────────────────────────────────────────────────

# Strip pacman's "1:1.2.3-4" epoch and -pkgrel → "1.2.3"
_strip_pacver() {
    sed -E 's/^[0-9]+://; s/-[0-9]+$//'
}

# major.minor from a full semver-ish string
_mm() {
    echo "$1" | awk -F. '{print ($1==""?"0":$1)"."($2==""?"0":$2)}'
}

# Get pacman version for a pkg (empty if not installed)
_pacver() {
    pacman -Q "$1" 2>/dev/null | awk '{print $2}' | _strip_pacver
}

# ── detect hyprland ───────────────────────────────────────────

HYPR_FULL=""
if command -v hyprctl >/dev/null 2>&1; then
    HYPR_FULL=$(hyprctl version 2>/dev/null \
                | grep -oE 'Tag: v?[0-9]+(\.[0-9]+)+' | head -1 \
                | sed 's/Tag: v\?//')
fi
[ -z "$HYPR_FULL" ] && HYPR_FULL=$(_pacver hyprland)
[ -z "$HYPR_FULL" ] && HYPR_FULL=$(_pacver hyprland-git)
[ -z "$HYPR_FULL" ] && { echo "✗ hyprland not detected (need hyprctl or pacman -Q hyprland)" >&2; exit 3; }

# ── detect quickshell ─────────────────────────────────────────
# -git packages report as e.g. "0.2.0.r123.g521ece4" — keep .x.y for pin

QS_FULL=$(_pacver quickshell-git)
QS_PKG="quickshell-git"
if [ -z "$QS_FULL" ]; then
    QS_FULL=$(_pacver quickshell)
    QS_PKG="quickshell"
fi
[ -z "$QS_FULL" ] && { echo "✗ quickshell / quickshell-git not detected" >&2; exit 3; }

# For -git, the version string is like "0.2.0.r123.g521ece4"; take the
# leading three dotted numerics only, so the major.minor pin stays sane.
QS_NUMERIC=$(echo "$QS_FULL" | grep -oE '^[0-9]+(\.[0-9]+){0,2}')
[ -z "$QS_NUMERIC" ] && QS_NUMERIC="$QS_FULL"

# ── detect Qt6 stack ──────────────────────────────────────────

QT6_DECL=$(_pacver qt6-declarative)
QT6_WAYL=$(_pacver qt6-wayland)
QT6_5C=$(_pacver qt6-5compat)
QT6_SVG=$(_pacver qt6-svg)

for v_name in "qt6-declarative:$QT6_DECL" "qt6-wayland:$QT6_WAYL" \
              "qt6-5compat:$QT6_5C" "qt6-svg:$QT6_SVG"; do
    n=${v_name%%:*}; v=${v_name#*:}
    if [ -z "$v" ]; then
        echo "✗ $n not installed — install via bootstrap.sh first, then re-run this." >&2
        exit 3
    fi
done

# ── distro / kernel (informational only) ──────────────────────

DISTRO_FULL=""
[ -r /etc/os-release ] && DISTRO_FULL=$(. /etc/os-release; echo "${PRETTY_NAME:-unknown}")
KERNEL_FULL=$(uname -r 2>/dev/null || echo unknown)

# ── compose ───────────────────────────────────────────────────

TS=$(date -Iseconds)
HOST=$(hostname 2>/dev/null || echo unknown)

read -r -d '' CONTENT <<EOF || true
# ═══════════════════════════════════════════════════════════════
# Zen Shell version lock
# ═══════════════════════════════════════════════════════════════
# Auto-generated by scripts/zen-make-versions-lock.sh
#   on $TS
#   from $HOST
#
# Format:
#   <pkg>=<major.minor>           ← enforced (patch .X floats freely)
#   <pkg>__full=<full-version>    ← informational ("tested against")
#
# Override at install time:
#   ZEN_FORCE_VERSIONS=1 ./install.sh
# ═══════════════════════════════════════════════════════════════

# ── Compositor ──
hyprland=$(_mm "$HYPR_FULL")
hyprland__full=$HYPR_FULL

# ── QML runtime host ($QS_PKG) ──
quickshell=$(_mm "$QS_NUMERIC")
quickshell__full=$QS_FULL
quickshell__pkg=$QS_PKG

# ── Qt6 stack ──
qt6_declarative=$(_mm "$QT6_DECL")
qt6_declarative__full=$QT6_DECL

qt6_wayland=$(_mm "$QT6_WAYL")
qt6_wayland__full=$QT6_WAYL

qt6_5compat=$(_mm "$QT6_5C")
qt6_5compat__full=$QT6_5C

qt6_svg=$(_mm "$QT6_SVG")
qt6_svg__full=$QT6_SVG

# ── Informational baseline ──
distro__full=$DISTRO_FULL
kernel__full=$KERNEL_FULL
EOF

if [ "$DRY" = "1" ]; then
    echo "# DRY RUN — would write to: $OUT"
    echo "$CONTENT"
    exit 0
fi

# Atomic write
TMP="${OUT}.tmp.$$"
echo "$CONTENT" > "$TMP"
mv "$TMP" "$OUT"

echo "  ✓ versions.lock written → $OUT"
echo ""
sed -n '/^hyprland=/,/^kernel__full=/p' "$OUT"
